version: '3.1'
services:
    rhs:
      image: ghcr.io/iden3/reverse-hash-service:latest
      build:
        context: ./
        dockerfile: ./Dockerfile
      restart: always
      environment:
        RHS_DB: "host=db password=${POSTGRES_PASSWORD:-secret} user=${POSTGRES_USER:-iden3} database=rhs"
      ports:
        - ${RHS_PORT:-8080}:8080
      networks:
        - rhs_network
      depends_on:
        - db


    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-secret}"
        POSTGRES_USER: "${POSTGRES_USER:-iden3}"
        POSTGRES_DB: rhs
      ports:
        - ${POSTGRES_PORT:-5432}:5432
      volumes:
        - ./.postgres-data:/var/lib/postgresql/data
      networks:
        - rhs_network

networks:
  rhs_network:

